#!/usr/bin/env python

import glob
files = glob.glob("./*.h")

print("#StereoCam Projects\n*autogenerated from @details in project header files -- make docs*\n*do not edit*\n")

start = 0;
for f in files:
    with open(f) as fp:
        cnt = 0
        print("##make PROJECT=" + f.replace("./","").replace(".h",""))
        for line in fp:
            if "@tested" in line:
                print("[Latest Tested Code](https://github.com/tudelft/stereoboard/commit/"+line.strip().lstrip("*").strip().replace("@tested","").strip()+")")
            if "@details" in line:
                start = 1
            if "*/" in line:
                start = 0
            if start:
                print(line.strip().lstrip("*").strip().replace("@details",""))
                cnt = cnt +1
        if cnt == 0:
            print("*UNDOCUMENTED*")
        print("")

