#!/usr/bin/env python

import glob
files = glob.glob("./*.h")

print("#StereoCam Projects\n*autogenerated -- do not edit*\n")

start = 0;
for f in files:
    with open(f) as fp:
        cnt = 0
        print("##PROJECT=" + f.replace("./","").replace(".h",""))
        for line in fp:
            if "@details" in line:
                start = 1
            if "*/" in line:
                start = 0
            if start:
                print(line.strip().lstrip("*").strip().replace("@details",""))
                cnt = cnt +1
        if cnt == 0:
            print("UNDOCUMENTED PROJECT")
        print("")

