
#ifndef STEREOBOARD_PARAMETERS_H_
#define STEREOBOARD_PARAMETERS_H_

/*****************
 * PARAMETERS FOR EACH STEREO BOARD THAT ARE ALSO USED IN THE MULTIGAZE CODE
 *****************/

// Settings for the matrix
#define MATRIX_WIDTH_BINS 10
#define MATRIX_HEIGHT_BINS 10
#define CLOSE_BOUNDARY 7
#endif /* STEREOBOARD_PARAMETERS_H_ */
